export const API_URL = 'http://172.20.10.9:7634';
export const API_URL_LOGIN = API_URL + '/login';
export const API_URL_REGISTRATION = API_URL + '/registration';
export const API_URL_GET_COURSES = API_URL + '/courses';
export const API_URL_POST_COURSES = API_URL + '/courses';
export const API_URL_GET_MEDICAMENTS = API_URL + '/medicaments';
export const API_URL_GET_MEDICAMENT = API_URL + '/medicaments/id=';
export const API_URL_GET_MEDICAMENTS_SEARCH = API_URL + '/medicaments/title=';
export const API_URL_POST_MEDICAMENTS = API_URL + '/medicaments';
export const API_URL_GET_TAKEMEDICINE = API_URL + '/takeMedicine';
